import type { Metadata } from "next";
import { Alex_Brush, Montserrat } from "next/font/google";
import { Header, Footer } from "@/components";
import "./globals.css";
import { NavContextProvider } from "@/context/NavContext";

const alexBrush = Alex_Brush({ 
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-alexBrush"
});

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NavContextProvider>
      <html lang="en">
        <body className={`${alexBrush.variable} ${montserrat.variable} overflow-x-hidden relative`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </NavContextProvider>
  );
}
